services:
  - type: web
    name: crocheted-money-api
    env: python
    region: ohio
    plan: free
    runtime:
      semver: ^3.11
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn --chdir server app:app
    envVars:
      - key: DATABASE_URL
        scope: run
        value: mysql+pymysql://2RurtFwhAV4RWf5.root:Yc6ZEp84YHzJdoPG@gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?ssl=true
